server:
  port: 10001

spring:
  application:
    name: admin-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 0ee85244-9171-499c-9536-0337f01e5b3b
        cluster-name: wzp
        group: wzp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wzp?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  kafka:
    bootstrapServers: 127.0.0.1:9092
    consumer:
      groupId: myGroup

  elasticsearch:
    rest:
      username: my-application
      uris: 127.0.0.1:9200